version: "3.7"
services:
    # open-prompt-studio start
    open-prompt-studio:
        container_name: "open-prompt-studio"
        image: "open-prompt-studio:latest" # build by https://github.com/Moonvy/OpenPromptStudio
        environment:
            - TENCENT_SECRET_ID=AKIDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - TENCENT_SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - LOCAL_TRANSLATE_HOST=localhost:39011 # 自定义翻译服务地址，设置为你服务器最终访问地址
        ports:
            - "12833:12833" # 宿主 Web 页端口:容器端口
            - "39011:39011" # 宿主翻译服务端口:容器端口
        restart: on-failure:3 # always on-failure:3 or unless-stopped default "no"
    # open-prompt-studio end
